### ISSUE TITLE
List of resources

### ISSUE THREAD

**Issue by butterflyology** [Reproducible-Science-Curriculum/planning#6]
I went through the materials present in the Reproducible-Science-Curriculum repo and here is my impression:

Example:

- Repo-name
	- main topic 1
	- main topic 2

- **workshop-planning (general guidelines for content)**
	- Introduction / motivation
	- Directory and file organization
	- Literate programming
	- Version control
	- Automoation
	- Publication

- **rr-intro**
	- motivation 
	- Why R

- **organization-1**
	- naming files
	- file-organization

- **rr-literate-programming**
	- documenting data modification
	- Rstudio and Rmarkdown

- **rr-version-control**
	- version control with git and github
	- git and github particulars / tutorial
	- Rstudio and git integration

- **rr-automation**
	- Intro and motivation
	- functions
	- functions for data
	- functions for figures
	- testing

- **publishing**
	- type of access
	- type of license

**Comment by hlapp** [comment]
Spot on!
